### PR TITLE
Get client

### PR DESCRIPTION
**Pull request by rohe**
Using plain OIDC there are only two options regarding client_id: either it's set statically or it's received as the result of a
dynamic registration.
Under Federation OIDC there is a third state. If automatic registration is used the client_id is not set per OP neither is it 
registered with the OP. The up come of this was that attribute client_id was not set in the Client instance creating problem down the line. Adding and using the get_client_id() fixed this problem since the entity/client would know where to find the client_id.

### CODE REVIEW

**Comment by peppelinux** [comment]
We have to drop the support for py36 as here
https://github.com/IdentityPython/JWTConnect-Python-OidcMsg/pull/56

**Comment by peppelinux** [comment]
ok, if you agree I think that this PR is ready to be merged

**Comment by rohe** [comment]
I agree

**Comment by peppelinux** [comment]
Ok, it seems to me that we just have to drop py36 from the CI

meantime I approve this PR :)

**Review by peppelinux — APPROVED** [review]

**Comment by rohe** [comment]
Yepp

**Pull request merged**
