### PR TITLE
fixed session_iframe resource in userinfo response

### PR DESCRIPTION
**Pull request by peppelinux**
I fixed a bug introduced in my last commit.

### CODE REVIEW

**Comment by rohe** [comment]
This is outdated. I guess closing this and doing a new with the missing things would be the best way to go.

**Comment by peppelinux** [comment]
K, If I can help I can fix these conflicts, just tell me or close this

**Comment by peppelinux** [comment]
Merged with latest commits of mine.
Error messages are now more eloquent

**Comment by rohe** [comment]
I thought we agreed on closing this PR and starting a new from where the master is presently ?
I have a hard time knowing what will actually change if I apply this PR.
Sorry more work for you :-/

**Comment by peppelinux** [comment]
You're welcome

**Comment by peppelinux** [comment]
This PR starts from the HEAD of the current master, You can merge it I think. Just checked now

**Pull request closed without merging**
